import { describe, expect, it, vi, afterEach, beforeEach } from 'vitest'
import { arrangeShelves, completedIn, dateInput, parseDate, spineWidth, statistics, validateCompletion } from '../../src/utils/reading'
import { normalizeBook, searchBooks } from '../../src/services/books'
import { bookSearch } from '../../server/book-search'
import type { Book, ReadingRecord } from '../../src/types'
const book: Book = { id: 'one', isbn: '9788937460449', title: 'Test Book', authors: ['Test Author'], publisher: 'Test Publisher', thumbnail: '', pageCount: 300, genre: 'Fiction' }
const record = (id: string, finishedAt: Date): ReadingRecord => ({ id, bookId: book.id, userId: 'user', status: 'COMPLETED', startedAt: new Date(2025, 0, 1), finishedAt, rating: 4, createdAt: new Date(2025, 0, 1), updatedAt: finishedAt })
afterEach(() => { vi.unstubAllGlobals(); vi.unstubAllEnvs(); vi.useRealTimers() })
describe('reading calculations', () => {
  it('uses continuous bounded spine widths', () => { expect(spineWidth(301) - spineWidth(300)).toBeCloseTo(0.07); expect(spineWidth(1)).toBe(28); expect(spineWidth(10000)).toBe(66); expect(spineWidth(Number.NaN)).toBe(spineWidth(300)) })
  it('adds shelves without losing reading order', () => { const records = Array.from({ length: 5 }, (_, i) => record(String(i), new Date(2026, 0, i + 1))); const rows = arrangeShelves(records, [book], 95); expect(rows.map((row) => row.length)).toEqual([2, 2, 1]); expect(rows.flat().map((item) => item.id)).toEqual(records.map((item) => item.id)) })
  it('counts completed pages and genres', () => { const records = [record('1', new Date(2026, 0, 2)), record('2', new Date(2026, 0, 3)), { ...record('3', new Date(2026, 2, 5)), bookId: 'unknown', rating: 2 }, record('4', new Date(2025, 11, 31))]; const stats = statistics(records, [book, { ...book, id: 'unknown', genre: '\uBBF8\uBD84\uB958', pageCount: 120 }], 2026); expect(stats.count).toBe(3); expect(stats.pages).toBe(720); expect(stats.months.slice(0, 3)).toEqual([2, 0, 1]); expect(stats.genres).toEqual([['Fiction', 2]]); expect(stats.averagePagesPerDay).toBeGreaterThan(0); expect(completedIn(records, 2025)).toHaveLength(1) })
  it('validates completion values', () => { vi.useFakeTimers(); vi.setSystemTime(new Date(2026, 8, 18)); expect(validateCompletion(parseDate('2026-09-01'), parseDate('2026-09-18'), 4)).toBe(''); expect(validateCompletion(parseDate('2026-09-18'), parseDate('2026-09-01'), 4)).not.toBe(''); expect(validateCompletion(parseDate('2026-09-01'), parseDate('2026-09-18'), 0)).not.toBe(''); expect(dateInput(parseDate('2026-01-01'))).toBe('2026-01-01') })
})
describe('YES24 API boundaries', () => {
  let enrichBook: typeof import('../../src/services/books').enrichBook
  beforeEach(async () => { vi.resetModules(); ;({ enrichBook } = await import('../../src/services/books')) })
  it('uses the YES24 proxy for search results', async () => { const fetch = vi.fn().mockResolvedValue({ ok: true, json: async () => ({ books: [book], hasMore: false }) }); vi.stubGlobal('fetch', fetch); expect((await searchBooks('test', 1)).books).toHaveLength(1); expect(fetch).toHaveBeenCalledWith('/api/books?query=test&page=1', { signal: undefined }) })
  it('loads selected ISBN metadata once', async () => { const fetch = vi.fn().mockResolvedValue({ ok: true, json: async () => ({ book: { ...book, pageCount: 240, genre: '문학', usedFallback: false } }) }); vi.stubGlobal('fetch', fetch); expect(await enrichBook(book)).toMatchObject({ pageCount: 240, genre: '문학', usedFallback: false }); await enrichBook(book); expect(fetch).toHaveBeenCalledTimes(1); expect(fetch.mock.calls[0][0]).toBe('/api/books?isbn=9788937460449') })
  it('uses fallback metadata when detail fails', async () => { vi.stubGlobal('fetch', vi.fn().mockRejectedValue(new Error('offline'))); expect(await enrichBook({ ...book, pageCount: 900 })).toMatchObject({ pageCount: 300, genre: '\uBBF8\uBD84\uB958', usedFallback: true }) })
  it('normalizes YES24 fields and defaults', () => { expect(normalizeBook({ isbn13: '9788937460449', title: 'Test', author: 'Author 1, Author 2', pages: 420, categoryName: '국내도서-소설/시/희곡' })).toMatchObject({ id: '9788937460449', pageCount: 420, genre: '소설/시/희곡', authors: ['Author 1', 'Author 2'] }); expect(normalizeBook({ title: 'No ISBN' })).toMatchObject({ pageCount: 300, genre: '\uBBF8\uBD84\uB958' }) })
  it('caches repeated server searches', async () => { const fetch = vi.fn().mockResolvedValue({ ok: true, json: async () => ({ data: { items: [], currentPage: 1, pageSize: 20, totalCount: 0 } }) }); vi.stubGlobal('fetch', fetch); const query = `cache-${Date.now()}`; await bookSearch(query, 1, 'secret'); await bookSearch(query, 1, 'secret'); expect(fetch).toHaveBeenCalledTimes(1) })
  it('validates server requests and preserves rate limits', async () => { expect((await bookSearch('', 1, 'key')).status).toBe(400); expect((await bookSearch('book', 51, 'key')).status).toBe(400); expect((await bookSearch('book', 1)).status).toBe(503); vi.stubGlobal('fetch', vi.fn().mockResolvedValue({ ok: false, status: 429 })); expect((await bookSearch('book', 1, 'secret')).status).toBe(429) })
})
